# Generated by Django 5.2.5 on 2025-09-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_topicrequest_topic_name_and_more'),
        ('accounts', '0003_data_migration'),
    ]

    operations = [
    ]
